version: "3"

services:
  mongo:
    image: "mongo"
    volumes:
      - ./db:/data/db

  mongo-express:
    depends_on:
      - mongo
    image: "mongo-express"
    ports:
      - "8081:8081"

  server:
    stdin_open: true
    build:
      context: .
    environment:
      - PORT=8080
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=todo-tdd
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "8080:8080"

volumes:
  server:
  mongo:
